### ISSUE TITLE
How do I correctly create/edit a page with Macros?

### ISSUE THREAD

**Issue by CliffCawley** [dapplo/Dapplo.Confluence#10]
It seems I can only get the html content of a page.

If I take the content of one page and dump it to a new page, the output looks like the actual page output instead of the source. I.e. the original page has some macros embedded. I want to take a copy of that, tweak the macro params and other page content slightly and create a new page with that.

Is that possible?

**Comment by Lakritzator** [comment]
I never used macros, let me check that out.

**Comment by Lakritzator** [comment]
I misunderstood the "macro", of course we use them..

Yes, this **should** be possible, but I didn't test this yet.
To make this easier, I added a little change.

You will need  to do the following:

1. Before calling Content.GetAsync make sure you change the ConfluenceClientConfig.ExpandGetContent to make sure the right body representation is returned.
2. Call the Content.GetAsync to get your content
3. Create a Body object, with the value you need (I don't think its wise to post multiple body representations.
4. Call the CreateAsync with the Body in the signature (string type, string title, string spaceKey, Body body, long? ancestorId = null)

Possible values for the body representation are:
- body.editor
- body.export_view
- body.view
- body.storage
- body.anonymous_export_view
- body.styled_view

I think you need body.storage but it might be body.editor
Sorry, this you will need to figure out yourself.. 

You can see in the browser what the different representations return by playing around with this Uri:
```
https://confluence/rest/api/content/<your content id>?expand=body,body.editor
```

**Comment by Lakritzator** [comment]
@CliffCawley Did you have time to check this?

**Comment by Lakritzator** [comment]
@CliffCawley Anything?

**Comment by CliffCawley** [comment]
@Lakritzator So sorry for the extremely long silence, I couldn't investigate this as I had several hurdles to overcome and no time to spend investigating them.

I was finally able to get .net core running on the mac with the .net core 2 release and then I finally attempted the above.

You were right, body.storage was exactly what I needed and I was able to perfectly create a page (duplicating body content and tweaking it).

Thanks so much, you can close this!

Perhaps a wiki entry using the information above?

**Comment by CliffCawley** [comment]
Oh, will you be updating the ConfluenceClientConfig.ExpandGetContent so that it's not global?

(I'm also finally using your nuget packages, now that I don't have to create a backported project file to get it working in .net framework) :D

**Comment by Lakritzator** [comment]
I forgot to close this some time ago, the API is now allowing you to supply the expand fields.
