### ISSUE TITLE
Strange behavior with page versions

### ISSUE THREAD

**Issue by frank71336** [dapplo/Dapplo.Confluence#11]
I've done something like this:

```
var newBody = new Body
{
	Storage = new BodyContent
	{
		Value = "Test 123",
		Representation = "storage"
	}
};

content.Body = newBody;
content.Version.Number++;            // old value:  11, new value 12
var result = await confluenceClient.Content.UpdateAsync(content);
```

This worked fine, I think. I can see the changes to the page in Confluence and in Page History. Newest page version now is 12, sounds good.

Now the problem:

```
var query = Where.And(Where.Space.Is("Test"), Where.Type.IsPage, Where.Title.Contains("API-TEST")); 
var searchResults = await confluenceClient.Content.SearchAsync(query);
var searchResult = searchResults.Single();
```
**=> searchResult.Version.Number = 11      //   !!! why 11 ?**

```
var query = Where.Title.Contains("API-TEST"); 
var searchResults = await confluenceClient.Content.SearchAsync(query);
var searchResult = searchResults.Single();
```
**=> searchResult.Version.Number = 8      //  !!! why 10 ?**

Depending on the query I get different results. Although in both cases only one search result is returned, I get different version numbers, both wrong.

And even worse:

```
var id = searchResult.Id;
var content = await confluenceClient.Content.GetAsync(id.ToString());
```
**=> content.Version.Number = 8  // !!! why 8 ?**

So "await confluenceClient.Content.SearchAsync(query);" and "await confluenceClient.Content.GetAsync(id.ToString());" return different values although I use the given ID from the first call for the second call...

It seems that the numbers returned change from time to time. Maybe this is some kind of timing problem? Or some buffer problem? I tried to check this with Fiddler but the Confluence server is accessible by https only...

Maybe I make some mistakes here (due to the poor documentation)? Btw. the project url given in the nuGet package doesn't work: http://www.dapplo.net/blocks/Dapplo.Confluence/ (page not found)

**Comment by Lakritzator** [comment]
First, I don't think you can specify the version of the content, the server should set this itself.

The behavior you describe is very weird, I will check what happens. If I can reproduce it.

The documentation hasn't been published, which I really should. And my site is still in a state of something I threw together in  a few hours... but it's a project I made to upload attachments to confluence from Greenshot. I don't get money for it, so I fix things when a bug report comes in.

**Comment by Lakritzator** [comment]
I tried to reproduce this, but couldn't.
I will write down some steps to troubleshoot this, you can activate logs...

The URL that is called to get the search content is, for example:

`https://greenshot.atlassian.net/wiki/rest/api/content/search?cql=(space%3D"TEST" and type%3Dpage and title~"Test Home")&limit=20&expand=version%2Cspace%2Cspace.icon%2Cspace.description%2Cspace.homepage
`

Maybe you can tell me what version of Confluence you are using? I tested against the cloud and also against something which is older. But who knows, maybe there is an error.

It's also possible that setting the content version number broke confluence, seen weirder bugs during my life.. 😄

**Comment by frank71336** [comment]
> First, I don't think you can specify the version of the content, the server should set this itself.

I think I must provide the correct (new) version number when changing content.

If I do this...

```
var newBody = new Body
{
	Storage = new BodyContent
	{
		Value = "....",
		Representation = "storage"
	}
};

content.Body = newBody;
// content.Version.Number++;                                        <---- leave version unchanged
var result = await confluenceClient.Content.UpdateAsync(content);
```

... then I get an exception:

**You're using an invalid version of the updated content. The latest version is 12**

I think ,Confluence API help says the same:

https://docs.atlassian.com/confluence/REST/latest/#content-update

> Updates a piece of Content, including changes to content status: To update a piece of content you must increment the version.number, supplying the number of the version you are creating.

**Comment by Lakritzator** [comment]
Ah thanks, I overlooked that the version needs to be supplied. Maybe I should add an option to have this made automatically... weird that they do it this way, but okay.

I still can't reproduct your problem, if I update the content via the confluence site I get the most recent version whatever search I use.

**Comment by frank71336** [comment]
We're using Confluence **5.7.1**. Update to 6.2.1 is scheduled for the next few weeks.

This morning, page version in Confluence history is 12.

```
var searchResults = await confluenceClient.Content.SearchAsync(query);
```
returns page version 12.

```
searchResult = await confluenceClient.Content.GetByTitleAsync("xxx", "xxx");
```
retuns page version 12.

```
var content = await confluenceClient.Content.GetAsync(id.ToString());
```

retuns page version 12.

So the problem **seems to be gone over the weekend**.

**But then I updated the page:**

```
var newBody = new Body
{
	Storage = new BodyContent
	{
		Value = newText,
		Representation = "storage"
	}
};

content.Body = newBody;
content.Version.Number++;
var result = await confluenceClient.Content.UpdateAsync(content);
```

Now I have - as expected - version number **13** in Confluence page history.

Now repeating all the steps obove unfortunatelly shows the same behaviour as last week:

`var searchResults = await confluenceClient.Content.SearchAsync(query);`
**still returns version number 12 which is again wrong.**

Calling the API directly returns the correct value:
`https://srv01cf1/rest/api/content?title=API1234&expand=version`
**=> number: 13**

I now have access to our Confluence test server for the 6.2.1 version. **Using this server everything works correct.**

So this problem is either related the Confluence version or the server itself?

As the problem seems to go away over the weekend I still think this is a **caching problem of some kind?** But as the direct call of the API returns the correct content this would have to be a caching problem of either Visual Studio or Dapplo.Confluence ?

**May I suggest to ignore this problem until we have the new Confluence version online? Then we can see what happens. (If you want to try any logging tests I will assist you of cause.)**

**Comment by Lakritzator** [comment]
I will check the caching, this was an issue in one of my libs and I might have forgotten to do this for Dapplo.Confluence.

**Comment by Lakritzator** [comment]
It can be the caching, good find...

The HttpClient uses caching by default, you can disable this by calling this before you start using the Confluence client:
HttpExtensionsGlobals.HttpSettings.RequestCacheLevel = RequestCacheLevel.NoCacheNoStore;

I will activate this by default, as for the library this makes no sense.

**Comment by Lakritzator** [comment]
Published a change to disable the caching, as I remarked this doesn't work on .NET Core (there is no setting I know of) and I will to check if I can do something there.

**Comment by frank71336** [comment]
**This seems to be the solution! I added the "HttpExtensionsGlobals.HttpSettings.RequestCacheLevel = RequestCacheLevel.NoCacheNoStore;" and everything seems to be fine now. I tried it serveral times without any error.**

I can't say anything regarding .NET Core as this isn't used yet.

_There seems to be another problem, but this is a problem of the Confluence API itself:_

https://community.atlassian.com/t5/Confluence-questions/Updating-a-confluence-page-with-Rest-API-problem-with-ancestors/qaq-p/74667

_When changing the content you must modify the 'Ancestors' property. Otherwise the page will move in the Confluence project hierarchy! I found the following line to be necessary:_

`content.Ancestors = new List<Dapplo.Confluence.Entities.Content>() { content.Ancestors.Last() };`

_So discard the 'Ancestors' list and replace it with the last element of the list. Then you can save the modified content and the page will stay where it is._

**Comment by Lakritzator** [comment]
Thanks for the information, I did see something like that while researching for #9 (this is where the Ancestors was added)

In general the Confluence API is less than optimum, there seems to be quite a lot of "weirdness" in it.
