### ISSUE TITLE
OAuth Token Support

### ISSUE THREAD

**Issue by SeriousM** [dapplo/Dapplo.Confluence#13]
Hi! Your Dapplo.Jira package supports the use (and implicit request) of oauth tokens.
Is it possible to enable the same functionality for the confluence package?
Currently only basic authentication is possible.

That would be awesome!

Thank you

**Comment by Lakritzator** [comment]
I will need to check this, Atlassian's Confluence API is (was?) a lot less advanced as the JIRA API.

**Comment by Lakritzator** [comment]
Am I correctly assuming you already got the OAuth for Jira working? This means you know how it works...
I have cloned the functionality of Jira, but I have not yet been able to free some time to test this... if you could?

The functionality was added in Dapplo.Confluence 0.5.20, and "should" work exactly like that in Dapplo.Jira.

**Comment by SeriousM** [comment]
I didn't tested your solution yet but I guess it wont work.
Why: the oauth authorization for confluence requires that the oauth parameters are send as get parameters instead of head parameters. I know, it SHOULD work the same because it's the same company, but it's not the case.

**Comment by Lakritzator** [comment]
Ah, you are referring to this:
https://community.atlassian.com/t5/Questions/Confluence-Oauth-Authentication/qaq-p/331326

How did you know?

**Comment by Lakritzator** [comment]
Thanks, the comments were "overlapped"... I will now read your information :smile:

**Comment by Lakritzator** [comment]
I made some changes, which in theorie might work, to Dapplo.HttpExtensions which was made for the Http communications. I don't have a system where I can test this though.

**Comment by SeriousM** [comment]
Ok, I'll give it a try but I'm currently on vacation and can test it in about two weeks. Thank you!

**Comment by Lakritzator** [comment]
Okay, maybe I can get it working before that time 😄

**Comment by Lakritzator** [comment]
@SeriousM I unfortunately didn't manage to setup a test system to test the change I made to get OAuth on Confluence working. Did you have time to look at it? The changes are available in 0.6.5

**Comment by Lakritzator** [comment]
@SeriousM Anything?

**Comment by SeriousM** [comment]
I'm sorry, I have no time to do the testing on my side.
