### ISSUE TITLE
Dapplo.Confluence.Query.Where.Parent.Is accepts int instead of long. 

### ISSUE THREAD

**Issue by milleym** [dapplo/Dapplo.Confluence#14]
Type mismatch: 

Dapplo.Confluence.Query.Where.Parent.Is accepts int. 

Dapplo.Confluence.Entities.Content.Id returns a long.

**Comment by Lakritzator** [comment]
Thanks for reporting this, fixed this in Dapplo.Confluence 0.5.15 which should be indexed on NuGet in a few minutes from now.
