### ISSUE TITLE
Add support for Labels

### ISSUE THREAD

**Issue by CliffCawley** [dapplo/Dapplo.Confluence#17]
Would it be possible to add support for labels?
Looks like it's part of the metadata for a page: https://docs.atlassian.com/confluence/REST/latest/#content/{id}/label-addLabels

**Comment by Lakritzator** [comment]
I have made the changes, but the build is failing due to problems with Cake (incompatible versions).
First that needs to be solved... otherwise no nuget packages.

**Comment by CliffCawley** [comment]
No worries, looking forward to the nuget packages 👍

**Comment by Lakritzator** [comment]
I just released 0.6.10, the label functionality is added to the "ContentDomain" and can be used as follows:

- Create labels for content: confluenceClient.Content.AddLabelsAsync(long contentId, IEnumerable<Label>) for creating the enumerable you can do something like this on an string array called "labels": labels.Select(label => new Label{Name = label})
- Get the labels for content: confluenceClient.Content.GetLabelsAsync(long contentId)
- Delete labels for content: confluenceClient.Content.DeleteLabelAsync(long contentId, string)

See: https://github.com/dapplo/Dapplo.Confluence/blob/master/src/Dapplo.Confluence.Tests/ContentTests.cs#L134

I am considering:
- Create label for content: confluenceClient.Content.AddLabelAsync(long contentId, string)
And also modifying the Content "entity" to have an explicit cast to long, making it easier to use a content object everywhere where an ID is needed.

**Comment by CliffCawley** [comment]
Works perfectly @Lakritzator thanks!

**Comment by CliffCawley** [comment]
I like your idea for `confluenceClient.Content.AddLabelAsync(long contentId, string)`, you could also include `confluenceClient.Content.AddLabelAsync(long contentId, string[])` or `confluenceClient.Content.AddLabelAsync(long contentId, IEnumerator<string>)` for helper shortcuts
