### ISSUE TITLE
How to get a PAGE TREE of space

### ISSUE THREAD

**Issue by quangbinhit** [dapplo/Dapplo.Confluence#20]
Dear,

I want to get a PAGE TREE of space.  It can support for this action?

Regards,
Binh

**Comment by Lakritzator** [comment]
Sorry for the delay, I started with a new job and than my laptop broke down.
About your question, I'm not sure, need to check... 😊

**Comment by Lakritzator** [comment]
I added a new method to the SpaceDomain: Space.GetContentsAsync("<spacekey>");
See: https://developer.atlassian.com/cloud/confluence/rest/?_ga=2.79668370.74649793.1513115044-949371064.1513115044#api-space-spaceKey-content-get

Should be available in 0.7.6 or later, which is build while I am writing this.

**Comment by Lakritzator** [comment]
To use this, you get a SpaceContents instance which has pages & blogposts.

You can use Linq and other IEnumerable logic to get whatever you need.
Important, you can use the ancestors of the page.

For instance, just an example: spaceContents.Pages.First().Ancestors.First()

**Comment by quangbinhit** [comment]
Dear Lakritzator,

Thank for your support!
I will try it.

Regards!

**Comment by Lakritzator** [comment]
Did it help?

**Comment by Lakritzator** [comment]
Can I close this?

**Comment by Lakritzator** [comment]
Closing due to disinterest of the issue creator.
