### ISSUE TITLE
Create Page

### ISSUE THREAD

**Issue by A-R-FERREIRA** [dapplo/Dapplo.Confluence#21]
Hi, 
With master version i have a problem, because ContentTypes serialization, EnumMember "page" is sending as "Page" and confluence return an error (not content type allow).
Thanks

**Comment by Lakritzator** [comment]
I will look at it , changing the underlying framework will not work though.

**Comment by Lakritzator** [comment]
I made a change to the underlying Dapplo.HttpExtensions which fixes the issue.
The update is available as Dapplo.Confluence 0.7.5.

Best wishes,
Robin

**Comment by Lakritzator** [comment]
P.S.
Sorry for the delay, my laptop broke down and made it impossible to change code for 2 weeks.
