### ISSUE TITLE
OAuth Step by Step Guide

### ISSUE THREAD

**Issue by kst83** [dapplo/Dapplo.Confluence#23]
Hello,

could you please post a step by step guide on how to sign in using OAuth?
This would be really helpful to get things started.

Best regards
Klaus

**Comment by kst83** [comment]
Seems Oauth isn't needed since I could login with user/pw with a python client.

**Comment by Lakritzator** [comment]
If you look at the main project page, like here: https://github.com/dapplo/Dapplo.Confluence
You see the example of how to use the library with a username & password.
There is no NEED to use OAuth, except that it reduces the possibility that someone gets your credentials.

You can also look at the different unit test cases for more examples.
