### ISSUE TITLE
Content.UpdateAsync not working

### ISSUE THREAD

**Issue by kst83** [dapplo/Dapplo.Confluence#24]
I'm currently trying to update a page I retrieved with searchAsync.
I'm working in synchronous mode.
For some reason, Content.UpdateAsync doesn't write anything to the page, even though there is no exception raised.
What am I doing wrong?
```
User confluenceUser = confluenceClient.User.GetCurrentUserAsync().Result;
            var searchResult = confluenceClient.Content.SearchAsync(query, limit: 10).Result;
            foreach (var result in searchResult.Results)
            {
                Console.WriteLine(result.Title);
                Content content = confluenceClient.Content.GetAsync(result.Id).Result;
                String bodyViewValue = content.Body.View.Value;
                Match match = Regex.Match(bodyViewValue, "<p>User:\\s([^>]+)<\\/p>");
                if (match.Success) // User-Metadaten erkannt
                {
                    String user = match.Groups[1].Value;
                    bodyViewValue = Regex.Replace(bodyViewValue, "<p>Abteilung:\\s*[^<]*</p>", "<p>Abteilung: TEST1</p>");
                    bodyViewValue = Regex.Replace(bodyViewValue, "<p>Position:\\s*[^<]*</p>", "<p>Position: TEST1</p>");
                    if(bodyViewValue != content.Body.View.Value)
                    {
                        content.Body.View.Value = bodyViewValue;
                        content.Version.Number++;
                        content.Version.When = DateTimeOffset.Now;
                        content.Version.IsMinorEdit = true;
                        content.Version.Message = "Updated User Details";
                        content.Version.By = confluenceUser;
                        confluenceClient.Content.UpdateAsync(content).Wait();
                    }
                }
            }
```

**Comment by Lakritzator** [comment]
I don't understand why someone would call async code without using async features.

Anyway, back to the main question.

This is actually badly documented, both in the Confluence documentation as in my library:
You can't update the view but should change the storage.
This means, for your code, use **content.Body.Storage.Value** instead of content.Body.View.Value

But to get the body.storage value, you need to set ConfluenceClientConfig.ExpandGetContent to {"body", "body.view", "body.storage", "version"}

Let me know if this works!

I am currently changing the GetAsync method signature so you can supply this directly without changing the defaults. Will update this issue as soon as this works and I published it.

**Comment by Lakritzator** [comment]
Released version 0.7.10

You can change the line:
`
Content content = confluenceClient.Content.GetAsync(result.Id).Result;
`
To:
`
Content content = confluenceClient.Content.GetAsync(result.Id, ConfluenceClientConfig.ExpandGetContentWithStorage).Result;
`

And everywhere where you use "content.Body.View.Value" you should change it to "content.Body.Storage.Value".

Don't know if this works, as the storage might have a slightly different format.

**Comment by kst83** [comment]
Thank you very much, it worked just as you explained.

I'm not using async because there isn't anything to do apart form updating the pages and I only want to have one request at a time. The reason I still call async code is because I didn't see synchronous code in this library.

**Comment by Lakritzator** [comment]
Thanks for the feedback.
Can you tell me in what enviroment your use it? ASP.NET?
Just so I know where my stuff works? 😄 

Async doesn't mean you have multiple requests, the await takes care of this.
But it does free your UI (Forms / WPF) or ASP.NET thread, making your system more responsive.

I can only advice you to take a look at it, it pays off.. especially in UI applications.

**Comment by kst83** [comment]
I'm using it in a C# command line application.
Since there is no GUI responsiveness isn't an issue :)
