### ISSUE TITLE
How to use this library with a proxy server

### ISSUE THREAD

**Issue by kst83** [dapplo/Dapplo.Confluence#25]
Hello,

is there a way to use this library with a proxy server?

Best regards
Klaus

**Comment by kst83** [comment]
I've now tried to pass httpSettings to the confluenceClient:
´´´
  var httpSettings = new HttpSettings();
            httpSettings.ProxyUri = new Uri("https://myproxy:8080");
            httpSettings.UseDefaultProxy = false;
            httpSettings.UseProxy = true;
´´´

However I get the following error message:
ServicePointManager doesn't support proxys with https schema

If I use http protocol for the proxy Uri I get the following error message:
System.Net.WebException: The remote server returned an error: (403) Forbidden.

**Comment by Lakritzator** [comment]
Can you tell me anything about the environment you are using it from?
Like ASP.NET on Windows with the .NET Framework, or do you use it from dotnet core?
This is important, while some HTTP settings are not available on platforms without the .NET Framework.

The default is that the library uses the default system proxy, and the default system credentials.

I am guessing you can't use the default proxy. The 403 would suggest the credentials are not okay, maybe you need to specify them.

**Comment by kst83** [comment]
I'm on .NET 4.5 in a Windows command line application.
The system I want to run the application on doesn't allow connections to the outside except for those over a specific proxy.
The proxy doesn't need any password/user.

**Comment by Lakritzator** [comment]
Did you try setting httpSettings.UseDefaultCredentials to false?

**Comment by kst83** [comment]
Yes, even with that I get a 403 error.
I also tried httpSettings.UseDefaultCredentialsForProxy = false.

**Comment by Lakritzator** [comment]
Yes, you were right... UseDefaultCredentialsForProxy  is what I ment.

Can you discuss this with the person who setup your proxy, I know there are many things that can be wrong here..
e.g.
- The proxy only accepts certain user-agents
- **You might just get 403 from the server you are connecting to, not from the proxy**
- Maybe the proxy does need credentials

You might want to look with Fiddle, to track what is happening.

**Comment by Lakritzator** [comment]
Actually... a proxy should return 407 Proxy Authentication Required  when the credentials don't match...

**Comment by Lakritzator** [comment]
Did you check if the 403 came from the server, not the proxy?

**Comment by Lakritzator** [comment]
Ah, too bad, I hoped to clear this 😞 
A 407 would come from a proxy, a 403 should come from the Jira server you connected to, I still expect that there was an configuration issue.

If you are no longer trying to fix/troubleshoot this issue, can I close it?

**Comment by kst83** [comment]
Sure, closed this
