### ISSUE TITLE
Strong Assembly Names for NuGet Pakages

### ISSUE THREAD

**Issue by squadwuschel** [dapplo/Dapplo.Confluence#27]
Hi,

is it possible to add a version to NuGet with strong Assembly naming?

**Comment by Lakritzator** [comment]
There are many reasons contra strong naming, I never liked Strong naming anyway.
Here is a post I read back than in 2016:
https://www.pedrolamas.com/2016/03/01/still-strong-naming-your-assemblies-you-do-know-its-2016-right/

For me this would mean a lot of additional work without seeing a direct benefit. (I will need to modify all the dependencies)

Would this be a solution? https://github.com/brutaldev/StrongNameSigner

Maybe you can explain your need a bit more in details?

What I could offer, is code-signing this and my dependencies?

**Comment by squadwuschel** [comment]
I'm using it in my project, where I have to use strong named assemblies and so I've singed your assemblies with the above tool and I think there are more developers out there who have no choice they have to use strong named assemblies. I prefer no strong naming but its not possible at the moment. So it would be nice if your assemblies could be strong named too beside the not strong named version.

**Comment by Lakritzator** [comment]
Update:
I'm working on providing string named assemblies, I already have made all underlying assemblies use strong naming. Today I wanted to release this, but somehow my build fails due to networking issues... I hope to see this solved soon.

**Comment by Lakritzator** [comment]
Just released Dapplo.Confluence 0.8.5.

Major changes are strong naming and removed the support for everything before .NET 4.6.1 (kept netstandard as is)
