### ISSUE TITLE
SetAuthorization() never called 

### ISSUE THREAD

**Issue by mightyking7** [dapplo/Dapplo.Confluence#28]
In the ConfigureBehaviour() method of the ConfleunceClient class, the SetAuthorization() method is never called because the  _user and _pass fields are always null. SetBasicAuthentication() can be used to set the credential fields, however this method must be called after the call to Create(), which implicitly calls ConfigureBehaviour().

**Comment by Lakritzator** [comment]
I don't get what you are trying to say..

The ConfigureBehaviour creates a lambda which is called for every request and takes the _user and _pass fields (if set SetBasicAuthentication was called)  and enhances this with authentication data. You do not need to call this before the create, it works fine as is!
