### ISSUE TITLE
GetAllAsync() returns limited number of spaces

### ISSUE THREAD

**Issue by hamid-gh** [dapplo/Dapplo.Confluence#29]
Hi,
I have tested Dapplo.Confluence. When I call GetAllAsync() method (defined in SpaceExtensions.cs), it returns only 25 spaces. How can I eliminate this limitation?
Thanks.

**Comment by Lakritzator** [comment]
I have added Space.GetAllWithParametersAsync method which supports **all** the currently possible spaces parameters described here:
https://docs.atlassian.com/atlassian-confluence/REST/6.6.0/#space-spaces

E.g.
var spaces = await _confluenceClient.Space.GetAllWithParametersAsync(limit: int.MaxValue);

Unfortunately you cannot pass a value meaning all, so I tested this with int.MaxValue which seems to work..

Changes are available in Dapplo.Confluence 0.8.7
