### ISSUE TITLE
com.atlassian.confluence.api.service.exceptions.PermissionException: Not permitted to use confluence : null

### ISSUE THREAD

**Issue by kiranmadhav208** [dapplo/Dapplo.Confluence#35]
Hi there,

I'm using Dapplo.Confluence 0.7.17, suddenly I'm getting below error and unable to identify the issue. I'm using c#.net to get the data from the Confluence. 

**Error Message:**
`com.atlassian.confluence.api.service.exceptions.PermissionException: Not permitted to use confluence : null`

**Comment by Lakritzator** [comment]
You are at an older version, any chance you can upgrade so we can exclude the fact that I already fixed this?

**Comment by Lakritzator** [comment]
Another possibility is that the user you are using to use the API doesn't have the right permissions.

**Comment by Lakritzator** [comment]
Closing due to no feed back.
