### ISSUE TITLE
Hours and minutes separated by a '-' instead of ':'

### ISSUE THREAD

**Issue by mattgueit** [dapplo/Dapplo.Confluence#36]
An attempt to construct a query based on DateTime.
`IFinalClause query = Where.LastModified.After.DateTime(lastSuccessfulPollDateTime);`

Causes the following exception to be thrown:

`System.AggregateException: 'One or more errors occurred.'
Inner exception:
ConfluenceException: Could not parse cql : lastModified > "2019-06-11 09-00"

I believe it's because the hours and minutes are separated by a '-' rather than a ':'.

https://github.com/dapplo/Dapplo.Confluence/blob/6ea719dfec786255b4d88f47db470cc203b89ffd/src/Dapplo.Confluence/Query/DatetimeClause.cs#L206

**Comment by Lakritzator** [comment]
Fix is coming today.
