### ISSUE TITLE
Could not create SSL/TLS secure channel.

### ISSUE THREAD

**Issue by RobVess** [dapplo/Dapplo.Confluence#38]
Hi Rob,

I think Atlassian has updated Confluence security requirements. 
I have just started receiving "Could not create SSL/TLS secure channel.".

JIRA had this issue a week ago using the Atlassian.JIRA 4.0.3 library. 

The solution in that case with Atlassian.JIRA 4.0.3 library was:

```
        ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12
        Connection = JiraLib.Jira.CreateRestClient(BaseURI, UserName, Password)
```
I'm not sure what the equivalent solution would be with the Dapplo confluence Library.
Any pointers would be appreciated. 

Cheers (again),
RobV.

**Comment by Lakritzator** [comment]
Hi,

actually the line: `ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12` is exactly what you need. This depends a lot on the .NET Framework, Windows version and registry settings, but in general this should work.

I actually don't want to force a certain TLS version in my library, so I hope you are okay with having to call this yourself?

Best wishes,
Robin

**Comment by Lakritzator** [comment]
Did you solve this? Can I close the issue?

**Comment by RobVess** [comment]
Yes, sorry should have updated it.

`        ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12
        Connection = ConfluenceClient.Create(URL)

        Connection.SetBasicAuthentication(UserName, Password)
`

Works fine, I had tried it myself but I think I had a few other lines in the middle, put the statements next to each other, seems to work..
