### ISSUE TITLE
Having trouble with body property for basic sample code

### ISSUE THREAD

**Issue by ormeroda** [dapplo/Dapplo.Confluence#39]
I'm having trouble with this basic sample... The content.Body property is always null.
The content variable is set correctly as you can return the title etc, but body is always null

var confluenceClient = ConfluenceClient.Create(new Uri("https://confluence"));
confluenceClient.SetBasicAuthentication(username, password);
var query = Where.And(Where.Type.IsPage, Where.Title.Is("Test Page"))
var searchResult = await confluenceClient.Content.SearchAsync(query, limit:1);
foreach (var content in searchResult.Results)
{
	Debug.WriteLine(content.Body);
}

as below:

{Dapplo.Confluence.Entities.Content}
    Ancestors: null
    Body: null
    Container: null
    Expandables: Count = 9
    History: null
    Id: 140096212
    InternalId: "140096212"
    Links: {Dapplo.Confluence.Entities.Links}
    Metadata: null
    Space: {Dapplo.Confluence.Entities.Space}
    Title: "2019/04/29 SF"
    Type: Page
    Version: {Dapplo.Confluence.Entities.Version}

> page.Body
null

**Comment by devheroo** [comment]
I have the same issue , page body is null.
this is the case when I run SearchAsync or if I just loop through all pages of a namespace.
please let me know if you found any solution , Thanks

**Comment by Lakritzator** [comment]
The Confluence API by default doesn't return every detail, to reduce CPU and bandwith, you can configure this by using "expand" values. With the SearchAsync by default only the meta-data is returned and not the content. One calls this digest values.

There are two ways to solve this, one is to call GetContent on the result you want to have the details of. This is actually a very normal behavior for a lot of APIs.

The other is to specify the fields, in this case the body, you want to have when calling for the search. The default expand values are stored in the ConfluenceClientConfig, for the SearchAsync this is ExpandSearch. This needs to be extended with "body".
Either:
1. if you always want to have the body, you can set ExpandSearch before calling the SearchAsync
2. if you only want to have the body filled for a specific search, you can pass the values you want when calling the SearchAsync.

Hope this helps, let me know so I can close the issue.

**Comment by Lakritzator** [comment]
Oh, an example of SearchAsync with GetContent can be found here:
https://github.com/dapplo/Dapplo.Confluence/blob/master/src/Dapplo.Confluence.Tests/ContentTests.cs#L66

**Comment by devheroo** [comment]
Thanks so much @Lakritzator, This resolved my issue.

**Comment by Lakritzator** [comment]
Thanks for the heads up, I'm awaiting a reply from @ormeroda so I can close this as this person reported the issue.

**Comment by ormeroda** [comment]
Yes please close this ticket. Was looking for this info 5 months ago, and have since coded manually.

**Comment by Lakritzator** [comment]
Sorry you had to code it manually, I guess the library needs more documentation.

Okay, closing it. Thanks for the feedback.
