### ISSUE TITLE
Is there a way to create users?

### ISSUE THREAD

**Issue by wangyue2017** [dapplo/Dapplo.Confluence#40]
Is there a way to create users?

**Comment by Lakritzator** [comment]
The confluence REST API doesn't provide a way to do this.
Atlassian has a JIRA ticket for this, where you can track it: https://jira.atlassian.com/browse/CONFSERVER-57988

The workaround seems to be some kind of CLI, as described here: https://community.atlassian.com/t5/Confluence-questions/Rest-Api-to-add-user-to-group/qaq-p/1050148
But I didn't implement this.

I hope this helps, I cannot provide you with a solution for you.
