### ISSUE TITLE
Confluence returns 400 Bad request when given timestamps without fractional seconds

### ISSUE THREAD

**Issue by treet** [dapplo/Dapplo.Confluence#41]
Confluence returns 400 Bad Request in some cases when using this library due to Confluence always expecting timestamps with fractional seconds, even if the fraction is zero.

This behavior is reported as a bug here, but I'm sure Atlassian would try to argue it's not a bug: https://jira.atlassian.com/browse/JRASERVER-61378

## Example
* The date "2020-01-01 15:01:02.03 +02:00" is serialized by [SimpleJson](https://github.com/dapplo/Dapplo.HttpExtensions/blob/486ac782398091d18f9fc4923da394cfdb743ba3/src/Dapplo.HttpExtensions.JsonSimple/PocoJsonSerializerStrategy.cs#L57) as "2020-01-01T15:01:02.03+02:00" and is accepted by Confluence.
* The date "2020-01-01 15:01:02.00 +02:00" is serialized as "2020-01-01T15:01:02+02:00" (**without** fractional seconds) and is rejected by Confluence.

**Error message from Confluence:**
400 Bad Request
Invalid format: "2020-01-10T13:27:50+00:00" is malformed at "+00:00" (through reference chain: com.atlassian.confluence.api.model.content.Content["version"]->com.atlassian.confluence.api.model.content.Version["when"])

## Code that reproduces the error
```
public static async Task Main(string[] args)
{
    var confluenceClient = ConfluenceClient.Create(new Uri(CONFLUENCE_URL));
    confluenceClient.SetBasicAuthentication(CONFLUENCE_USERNAME, CONFLUENCE_PASSWORD);

    var content = await confluenceClient.Content.GetAsync(PAGE_ID, ConfluenceClientConfig.ExpandGetContentWithStorage);
    content.Body.Storage.Value = "New page text";
    content.Version.When = new DateTimeOffset(2020, 1, 1, 0, 0, 0, TimeSpan.Zero); // NOTE: No fractional seconds in date

    await confluenceClient.Content.UpdateAsync(content); // Will return 400 Bad Request
}
```

## Proposed solution
Change the serialization format of DateTimeOffset from  "yyyy-MM-dd\THH:mm:ss.FFFFFFF" to  @"yyyy-MM-dd\THH:mm:ss.fffffff", forcing the JSON serializer to always output fractional digits for seconds even if they are zero.

I could open a pull request with the proposed changes, but I'm not completely sure of the consequences or if there are better solutions here.

**Comment by Lakritzator** [comment]
Thanks for reporting this, I will check if the fix would have side effects.
Do give me some time, I have a lot of things and currently little time...

P.S.
I actually would like to get rid of SimpleJson...

**Comment by Lakritzator** [comment]
Actually you got me on the wrong foot, Dapplo.Confluence doesn't use SimpleJson.
Unless you are on an older version, there it might still be the case.
It uses Json.NET, so at least the fix should be easier than poking around in old ...

The bug is very much there, also in Json.NET

**Comment by Lakritzator** [comment]
Fix is available in version 0.9.7

**Comment by treet** [comment]
Yes sorry, I was running version 0.8.23. I just updated to 0.9.7 and tested the fix and it works. Thanks a lot for fixing this issue!

**Comment by Lakritzator** [comment]
Thanks for reporting it!
