### ISSUE TITLE
How do I add watchers to a Space?

### ISSUE THREAD

**Issue by jrodforthewin** [dapplo/Dapplo.Confluence#44]
As one of the Confluence admin at my company, I sometimes have to add groups of users to a space as watchers.
This can become quite tedious if there are a lot, which there.
I use this Nuget Package of yours quite a bit for creating automated pages and such and would like to know how I would add watchers?
I would cycle through the group and add them one by one on my side.

**Comment by Lakritzator** [comment]
I found a part of the API to enable a user to watch [content ](https://docs.atlassian.com/atlassian-confluence/REST/6.6.0/#user/watch-addContentWatcher) or [spaces](https://docs.atlassian.com/atlassian-confluence/REST/6.6.0/#user/watch-addSpaceWatch).
There is also a way to retrieve this... but to my knowledge this was added in 6.x, not sure exactly which version (seen it in 6.5).

Groups is also a thing, not supported by my project right now but should be an easy thing to add.

Your workflow would just be that yes, loop through the group members and have them watch a space or content. It seems the group concept is not integrated into the watch API, so it can only be done on an individual base.

Does this: https://developer.atlassian.com/cloud/confluence/deprecation-notice-user-privacy-api-migration-guide/
Cause any issues for you? I'm currently at loss how to identify people with their atlassian ID only... 

I do need some time to add the watch and group funtionality though, got Greenshot and other projects, and I have my work where I earn my living, got a kid/wife/dog/house too.

Maybe your **company** can sponsor me a bit?

Btw. might it make sense to have PowerShell support for your work?
Would that make your life easier, if you could script stuff?
I started PowerShell support for my Jira integration, I don't think many people are using it though..

**Comment by Lakritzator** [comment]
Of course if you, or someone you know, can make a Pull-Request for this, that would be great too.

**Comment by Lakritzator** [comment]
Here is the PR I'm working on for this:
https://github.com/dapplo/Dapplo.Confluence/pull/45

**Comment by Lakritzator** [comment]
Okay, I've spent most of my private time during the weekend to make this possible.
It should be available shortly, as Dapplo.Confluence 1.0.x

Do me a favor and let me know if this works for you, and also write if somethings could be optimized.

**Comment by jrodforthewin** [comment]
You are amazing, thank you sir.
The company I work for is pretty strict, I actually logged a ticket with them this morning to clone your code for me so that I could take a look at it and see how I could implement the change, however you beat me to it!!
I'll check out your code and get back to you!

**Comment by Lakritzator** [comment]
Just use the latest NuGet package and try out your stuff.
In the test cases I just added the basic functionality, so there is a bit of test coverage (the coverage percentage is currently not updated) and I know it works in general. This doesn't mean it will work for your use-case, so I'd love to get a bit of feedback.

The documentation is generated with the latest version and should be here: https://www.dapplo.net/Dapplo.Confluence/index.html
I still need to fix the scrolling a bit 🤷 
For instance [AddSpaceWatcher](https://www.dapplo.net/Dapplo.Confluence/api/Dapplo.Confluence.UserDomain.html#Dapplo_Confluence_UserDomain_AddSpaceWatcher_Dapplo_Confluence_IUserDomain_System_String_Dapplo_Confluence_Entities_IAccountIdHolder_System_Threading_CancellationToken_)

I still would like to add articles, but I have a job, kid, house, wife and dog, so I can only spent so much time on things that don't make money...

If your confluence is in the cloud, all APIs work, otherwise you will need to check the version.

Btw. For details on what is possible and what not via the Confluence APIs, look here: https://developer.atlassian.com/cloud/confluence/rest/
If something you need is missing, I can probably add it.

**Comment by jrodforthewin** [comment]
First of all, thank you for attending to this so quick, considering you do this for fun.  I had previously attempted to do this myself with an httpclient but what I kept experiencing is the user that I was running the post under, was the user that was being added as a watcher.  Despite me actually passing in the the user that I want to be added as a watcher.  This is when I pass the parameters in as a query string.  If I attempt to pass them in via a post, it seems I get a 403.

I've updated my nuget package and tested it out.
I'm not sure if it's because we're an on prem site, but I seem to be getting an error back, and it's doing the same as when I tried to write this code as explained in the paragraph above.  It adds the user I'm running as as a watcher, which has admin rights to the space and throws an error.  
We're running Confluence 6.12.2
The error is: 
StackTrace (apologies if there are typos, I had to type this out):
```
at Dapplo.Confluence.Internals.HttpResponseExtensions.HandleStatusCode[TError](HttpResponseWithError`1 response, HttpStatusCode[] expectedHttpStatusCodes in d :\a\1\s\src\Dapplo.Confluence\Internals\HttpResponseExtensions.cs:line 150
at Dapplo.Confluence.UserDomain.AddSpaceWatcher(IUserDomain confluenceClient, String spaceKey, IAccountHolder accountIdHolder, CancellationToken cancellationToken) in d:\a\1\s\src\Dapplo.Confluence\UserExtensions.cs:line 327
```
Source: Dapplo.Confluence
Message: OK(200)

**Comment by Lakritzator** [comment]
Why do you have to type it out❓

You are getting a 200 (OK) as an exception when there is no error, hmmm need to check that.
Probably some wrong error handling, although I have a test case I might have overlooked something.

For the fact that it adds the user you are using to modify the watchers, can you show the code you are using, you are passing the user which needs to be added how?

**Comment by jrodforthewin** [comment]
That is a good question :)
The company I work for has strict intellectual property regulations.  However, I got the OK to send you the code.
When debugging, I can see that is correctly retrieving a user within a group and passing that in accordingly
```
 try
                {
                    var users = await _confluenceClient.Group.GetGroupMembersAsync(group);
 
                    foreach (var user in users)
                    {
                        await _confluenceClient.User.AddSpaceWatcher(spaceKey, user);
                    }
                }
```

**Comment by Lakritzator** [comment]
I work for a bank, I know strict companies.
Thanks, that makes sense... and "should" work, either there is a bug in my code or in confluence.
I'll need a bit of time though, but for now I don't directly need anything from your side.

**Comment by Lakritzator** [comment]
It might be that the documentation is wrong.
It says [here](https://developer.atlassian.com/cloud/confluence/rest/#api-api-user-watch-space-spaceKey-post] that the return value of the REST API for the AddSpaceWatcher is a 204.
"204 Returned if the watcher was successfully created. No response body is returned."

So it seems we get an 200 (which means HTTP status OK), but as I specifically specified I expect a 204 this causes an exception. At least this works as designed 🤷 

About the other part of the issue, when retrieving the users for the group, we do need to have a filled accountId. Just want to make sure, maybe you have it at hand, can you check if the value is NOT the current user and NOT empty?

**Comment by jrodforthewin** [comment]
Oh I can see the problem.
With cloud it's like this:
`https://your-domain.atlassian.net/wiki/rest/api/user/watch/space/{spaceKey}?accountId={accountId}'`
However, with Server (which is what I'm using, actually Data Center) it's like this:
`POST http://example.com/confluence/rest/api/user/watch/space/SPACEKEY?username=jblogs`
Or
`POST http://example.com/confluence/rest/api/user/watch/space/SPACEKEY?key=ff8080815a58e24c015a58e263710000`

So it's actually expecting a different parameter to identify the user.
Source:
[](https://docs.atlassian.com/ConfluenceServer/rest/7.5.0/#api/user/watch-addSpaceWatch)

My humblest apologies for not picking this up sooner

**Comment by Lakritzator** [comment]
Just so you know why I ask, don't have access to a PC until later 😉

**Comment by Lakritzator** [comment]
Ah wait, that actually makes sense. Only the cloud version is bothered by privacy issues...

Back to the drawing board!!

Right now you'll also get a compile warning if you are using a user key/name, this is wrong...

I probably need to add version support so I can handle different features.

Thanks for pointing this out.

**Comment by jrodforthewin** [comment]
Sorry to have given you more work :D

**Comment by Lakritzator** [comment]
I've made some changes, it was actually quite [a lot](https://github.com/dapplo/Dapplo.Confluence/commit/7743c574095cefc7d931ad78cb6c3562af946720), so can you try again?

I really need a new development system, with 8GB it's not really capable of running Visual Studio 2019 and docker... I wanted to try to work with a local Confluence server for some tests, but it turned out so slow....

Anyway, let me know if that works for you.

**Comment by jrodforthewin** [comment]
Wohoooo... It works!!

I was very pleased to see that it was working, but I did have to manipulate the code in some places due to some minor bugs.
Very well done for not being able to test properly under your circumstances and for being so proactive in figuring this out.  This is sincerely appreciated! 

There are two bugs that I found.  I wanted to step through and see what was going on so that I could give you better info, but my resharper didn't give me that option.  So instead, I copied your code to my own class and tested it out.

Firstly, the line where it does this check:
Method: `AddSpaceWatcher`
`bool isCloudServer = await confluenceClient.IsCloudServer(cancellationToken)`
It's telling me it can't find the implementation.  I've doubled checked and could see due to inheritance that there is in fact an implementation, so this could be a me issue.

Then the most important bug:
Method: `CreateUserWatchUri`
The part where it does the inverse of the cloud code, it's doing a null /empty check on the userIdentifer.AccountId, which it finds is null, because I believe this field is only for Cloud.
If I modify the code to check for userkey instead, it works:
`if(string.IsNullOrEmpty(((User)userIdentifier).UserKey)) throw new ArgumentNullException(nameof(userIdentifier), ............ etc` 
However, since you're using username, we can probably do the check on that instead.

Again, please excuse the typos :)

I also had to upgrade to c# 7.1, but I think that is due to me copying over your code.  I believe I can go back to 7 if it becomes an issue.

Very well done sir!

**Comment by Lakritzator** [comment]
This proves I need to setup a local confluence server for testing...
It should be easy with docker, but I already mentioned the memory limitation I have.

Anyway, that was an easy fix, thanks for the clear analysis.

I pushed the commit with the fix right away and the package will be build / available in 10-30 minutes depending on NuGet indexing.

I really hope you can use the nuget package, copy/paste of code is not a nice thing and I cannot give much assistance.

About the other things:
The "find the implementation" sounds like a local issue, you probably forgot to copy some logic or didn't do a rebuild... or whatever.

I currently use C# 8, and will always use the latest C# version (soon C# 9, as was presented on the Microsoft Build event this week) as I don't see any reason to hold myself back on the language version. The version of the language doesn't have much influence on the final DLL, and Visual Studio Community is free so everybody who wants should be able to contribute.
Also this library was made to build on AzureDevops, and not locally (except for development), it should clone & build without issues if you have the correct setup, assuming "a fairly recent" VS 2019. I unfortunately cannot really support people with code issues when they don't clone 🤷

**Comment by jrodforthewin** [comment]
It definitely looks however as if the IsCloudServer call breaks on my side.

After doing some investigation, it seems to break when it does this call:
`var response = await systemInfoUri.GetAsAsync<HttpResponse<SystemInfoEntity>>(cancellationToken).ConfigureAwait(false);`
Class: MiscExtensions
Error:
```
Response status code does not indicate success: 404()
at Dapplo.HttpExtensions.HttpResponseMessageExtensions.HandleErrorAsync(HttpResponseMessage httpResponseMessage) in d:\a\1\s\src\Dapplo.HttpExtensions\HttpResponseMessageExtensions.cs:line 134
```

When I looked even deeper, I found it was trying to get system info, and this is the part where it breaks as it looks like Data Center doesn't have this as an endpoint.
I checked their docs and there isn't anything to do with checking the system info in there.
I found the url when using the network tab in Chrome and navigating on the confluence ui to the system info section, however it seems to require an admin username and password.
So we might need to assume that if it's a 404 then it's not cloud.. ugh, sounds gross.
What are your thoughts?

**Comment by Lakritzator** [comment]
Yes I  need to handle a 404 without throwing an error, actually this was supposed to work already.

I'll check this tonight...

**Comment by Lakritzator** [comment]
Ah, I had a crash of my PC before I pushed the previous changes, and I was missing the specific change which prevents the 404 error to propagate (I already added something a long time ago to ignore errors.

I found it and enabled it again for the GetSystemInfo

Try it out, I couldn't do more as it is time for bed.

**Comment by Lakritzator** [comment]
https://www.nuget.org/packages/Dapplo.Confluence/ version 1.0.6

**Comment by jrodforthewin** [comment]
I'm sorry to hear about your PC crashing 😱 
You are brilliant.
It's all working now.  I also doubled checked if the user already is a watcher, what it does and it doesn't seem to mind.
Thank you so much for this 🥇

**Comment by Lakritzator** [comment]
Thanks for the feedback, I find it important to know if my changes really solve the problem. Some people just don't respond anymore, for them it's finished and they leave "us" OSS developers hanging.

**Comment by jrodforthewin** [comment]
Well done @Lakritzator .  This definitely solved the problem and I am impressed at the level of engagement and dedication 💯 
Kudos to you!
