### ISSUE TITLE
Dependencies incompatible with non-Windows platforms

### ISSUE THREAD

**Issue by andxpto** [dapplo/Dapplo.Confluence#47]
I use MacOS and VS for Mac and I'm facing a problem that I think it's because some dependency related to `Dapplo.Confluence`. Also, I checked the dependencies tree and checked that `Dapplo.HttpExtensions.OAuth` contains Windows only dependencies.

>/usr/local/share/dotnet/sdk/3.1.300/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(5,5): Error NETSDK1073: The FrameworkReference 'Microsoft.WindowsDesktop.App' was not recognized (NETSDK1073) (my_app_name)

>/usr/local/share/dotnet/sdk/3.1.300/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(5,5): Error NETSDK1073: The FrameworkReference 'Microsoft.WindowsDesktop.App.WindowsForms' was not recognized (NETSDK1073) (my_app_name)

Do you want to move forward with this Windows-only approach?

Thanks

**Comment by Lakritzator** [comment]
Hi, I already wanted to move the oauth part into a separate library, to "Dapplo.Confluence.OAuth" as currently it work only on Windows anyway and adds a lot of dependencies for functionality which only a few people might use.

Just didn't get the time for it yet...

**Comment by andxpto** [comment]
Totally understandable. Thanks for your work and effort.

**Comment by Lakritzator** [comment]
I just published a new version of Dapplo.Confluence 1.0.12, this should be without the Windows dependencies. I moved the OAuth to Dapplo.Confluence.OAuth, but to be honest I don't even know if this still works as I cannot enable OAuth on my Confluence server. The Atlassian documentation about this is horrible, but that is a different story! 🤷 

Although the dependencies are gone, this doesn't mean it will work, I've never been able to test this on MacOS or Linux.

Can you have a try and let me know?

**Comment by andxpto** [comment]
Similar problem. But this time it's only related with the `Microsoft.WindowsDesktop.App`.

Also I didn't understand which dependency is the problem.

> /usr/local/share/dotnet/sdk/3.1.300/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(5,5): Error NETSDK1073: The FrameworkReference 'Microsoft.WindowsDesktop.App' was not recognized (NETSDK1073) (my_app_name)

**Comment by Lakritzator** [comment]
I think it has to do with the HttpExtensions library, I need to check how I can solve this.

**Comment by Lakritzator** [comment]
I also have a JIRA project, which uses the same base, I'd like to update that too.
If you can inform me when you are able to test this, I'd be very grateful.

**Comment by Lakritzator** [comment]
Hello @andxpto, did you manage to have a look if it now works?

**Comment by andxpto** [comment]
@Lakritzator sorry. Yesterday I installed it and it compiled, also I tried the `SearchAsync` (example in your README) and worked perfectly.

**Comment by Lakritzator** [comment]
Super, thanks for reporting this back.

Closing this issue, let me know if you have any other questions / issues.
