### ISSUE TITLE
Getting a Parent Page or The Hierarchy up until the Child!

### ISSUE THREAD

**Issue by RockyRocks** [dapplo/Dapplo.Confluence#54]
Hello, Is there a way to get the parent page from the child result? when you search for the page using a Title of the page?

``var pageResults = Client.Content.GetPageByTitle(spaceKey, "Test `Title"));
var parent = pageResults.FIrstorDefault().parentID (something like this? )``

Or is there a different way to get this info somehow from the client or from content?

**Comment by RockyRocks** [comment]
And Also if possible could you also add some documentation with regarding the search queries. Currently I see no way to search the body of the page using a "search text".

**Comment by Lakritzator** [comment]
I know the documentation is very sparse, in fact I assume that most users already know their way around confluence.

Maybe we should make a list of things one wants to do, write test cases for all of them and use them in one or more articles.

To answer your question directly, you can define a query, and execute it, like this:
```
var query = Where.And(Where.Space.Is("TEST"), Where.Type.IsPage, Where.Title.Contains("Test Home"));
var searchResults = await Client.Content.SearchAsync(query);
```
Example can be found here:
https://github.com/dapplo/Dapplo.Confluence/blob/master/src/Dapplo.Confluence.Tests/ContentTests.cs#L56

The parent is in the Ancestor value, but with most Atlassian APIs you will probably need to specify you want this data.
This information costs time to retrieve, you will get its parents, and its parents parents, right up to the root level of the containing space.
So you need to add the "ancestors" to the expand, which is for example available in the following API: https://github.com/dapplo/Dapplo.Confluence/blob/master/src/Dapplo.Confluence/ContentExtensions.cs#L281

I think it's the easiest to use the SearchDetails class, and without trying it in the IDE I would assume it looks something like the following:
```
var searchDetails = new SearchDetails(Where.And(Where.Space.Is("TEST"), Where.Type.IsPage, Where.Title.Contains("Test Home"))) {
  ExpandSearch = ConfluenceClientConfig.ExpandSearch.Concat("ancestors")
};
var searchPageResults = await Client.Content.SearchAsync(query);
var parentPage = searchPageResults .FIrstorDefault().Ancestors.First();
```

Hope this helps, and you have to time to try it out, I won't solve all the work for you 😉

**Comment by RockyRocks** [comment]
@Lakritzator  Thanks for the reply, Yes I started using `SearchDetails` yesterday after posting this query. Although with some documentation, I would have reached to this result bit sooner 👍 .
This API deserves some documentation. ;)
