### ISSUE TITLE
Don't notify watchers

### ISSUE THREAD

**Issue by JaydenMaalouf** [dapplo/Dapplo.Confluence#55]
Just wondering if you provide a way to not notify watchers on updates/creation of pages in a space?
We use this package to push a bunch of generated content and would like the ability to not notify watchers

**Comment by dostjh** [comment]
Setting `Version.IsMinorEdit = true` is what you're after, I believe.

**Comment by Lakritzator** [comment]
Thanks for answering that @dostjh, that is the correct answer.
I never tried it though...

Honestly, I find that you really have to look deep into the documentation to find this feature: https://developer.atlassian.com/cloud/confluence/rest/api-group-content/#api-wiki-rest-api-content-id-put
It's visible in the content response, if you click on it and than on the version, not even directly in the documentation for the request... how silly.
It's "better" documented in this JIRA issue: https://jira.atlassian.com/browse/CONFSERVER-38804

I'd be more than happy to add something in the API to simplify this, if there is a need.
A fluent Content API, or Content builder API, would probably help.
If you have suggestions, create an issue!

One thing which is important to know, AFAIK you can't supress notifications when deleting attachments: https://jira.atlassian.com/browse/CONFSERVER-39330
