### ISSUE TITLE
The code breaks with exception with 404 inside

### ISSUE THREAD

**Issue by klapatyivasyl** [dapplo/Dapplo.Confluence#59]
Hello, I have the following code:
```
var confluenceClient = ConfluenceClient.Create(new Uri("https://{domain}.atlassian.net/confluence/"));
string searchQ = "Р";
confluenceClient.SetBasicAuthentication("{email}", "{password}");
var query = Where.And(
    Where.Title.Contains(searchQ),
    Where.Text.Contains(searchQ));
var spaces = await confluenceClient.Space.GetAllAsync();
var searchResult = await confluenceClient.Content.SearchAsync(query, pagingInformation: new()
{
     Limit = 100,
      Start = 1,
});
```

Every time when I try to run it, the excpetion fails on commands which make request(``` var spaces = await confluenceClient.Space.GetAllAsync(); ``` for example)
I suppose I have a wrong URL, then the questionis: Which is the right URl for accessing the api? There are no examples in the internet which tell something in this way
Thanks in advance

**Comment by Lakritzator** [comment]
For Greenshot I had to use the link https://greenshot.atlassian.net/wiki, 
So, I'd advice to use https://{domain}.atlassian.net/wiki
Please try.

**Comment by klapatyivasyl** [comment]
Yes,it works, the 404 didnt apear anymore. Thanks!
But now the error is 401 while the credentials are right(in ``` confluenceClient.SetBasicAuthentication("{email}", "{password}");```  I set my right credentials)

**Comment by Lakritzator** [comment]
You will need to generate an API token as password, so your PW will not be in your code and you can disable the usage without changing your PW.
Generate it here: https://id.atlassian.com/manage-profile/security/api-tokens
Copy the value (there is a button for it) and use this as the password in your code.

I should really document that, it was added later.

**Comment by Lakritzator** [comment]
So, I actually documented this in the readme.md, so at least it can be found somewhere.

@klapatyivasyl let me know if you got it working, so I can close this issue.

**Comment by klapatyivasyl** [comment]
Everything works now, great thanks for you and your fast replies!
