### ISSUE TITLE
Add functionality to search items by tags

### ISSUE THREAD

**Issue by klapatyivasyl** [dapplo/Dapplo.Confluence#60]

**Comment by Lakritzator** [comment]
You probably mean labels, and this functionality is already there.

An example:
        var query = Where.And(Where.Space.Is("yourspace"), Where.Label.Is("yourlabel"), Where.Type.IsPage));
        var searchResults = await ConfluenceTestClient.Content.SearchAsync(query);

Home this helps?

**Comment by klapatyivasyl** [comment]
> You probably mean labels, and this functionality is already there.
> 
> An example: var query = Where.And(Where.Space.Is("yourspace"), Where.Label.Is("yourlabel"), Where.Type.IsPage)); var searchResults = await ConfluenceTestClient.Content.SearchAsync(query);
> 
> Home this helps?

Yes, thanks.

**Comment by Lakritzator** [comment]
Closing this, as I think your question is answerer.
