### ISSUE TITLE
Simple example code fails?

### ISSUE THREAD

**Issue by CliffCawley** [dapplo/Dapplo.Confluence#8]
I'm having some difficulties creating a test project with your example code:

```
public static void Main(string[] args)
{
    var confluenceClient = ConfluenceClient.Create(new Uri("https://confluence"));
    confluenceClient.SetBasicAuthentication(username, password);
    var query = Where.And(Where.Type.IsPage, Where.Text.Contains("Test Home"));
    var searchResult = await confluenceClient.Content.SearchAsync(query, limit:1);
    foreach (var content in searchResult.Results)
    {
    	Debug.WriteLine(content.Body);
    }
}
```

If I use this and use either my confluence url or yours from your tests `https://greenshot.atlassian.net/wiki` then I get an `ArgumentOutOfRangeException` on the `var confluenceClient = ConfluenceClient.Create(new Uri("https://greenshot.atlassian.net/wiki"));` line.

Looks like it's expecting a logger?

```  System.TypeInitializationException: The type initializer for 'Dapplo.HttpExtensions.HttpExtensionsGlobals' threw an exception. ---> System.TypeInitializationException: The type initializer for 'Dapplo.HttpExtensions.ContentConverter.BitmapHttpContentConverter' threw an exception. ---> System.ArgumentOutOfRangeException: Length cannot be less than zero.
Parameter name: length
  at System.String.Substring (System.Int32 startIndex, System.Int32 length) [0x0003b] in /private/tmp/source-mono-2017-02/bockbuild-2017-02/profiles/mono-mac-xamarin/build-root/mono-x86/mcs/class/referencesource/mscorlib/system/string.cs:1250 
  at Dapplo.Log.LogSource..ctor (System.String sourceFilePath) [0x0003d] in <c9dee3df7c07468ea1bdf234890e79f5>:0 
  at Dapplo.HttpExtensions.ContentConverter.BitmapHttpContentConverter..cctor () [0x00000] in <dda59d8d3e364ae480ed73721859421e>:0 
   --- End of inner exception stack trace ---
  at Dapplo.HttpExtensions.HttpExtensionsGlobals..cctor () [0x00015] in <dda59d8d3e364ae480ed73721859421e>:0 
   --- End of inner exception stack trace ---
  at Dapplo.HttpExtensions.HttpBehaviour..ctor () [0x00000] in <dda59d8d3e364ae480ed73721859421e>:0 
  at Dapplo.Confluence.ConfluenceClient..ctor (System.Uri confluenceUri, Dapplo.HttpExtensions.IHttpSettings httpSettings) [0x00043] in <c2e023c71b0d4013b45f2fad5d4ea254>:0 
  at Dapplo.Confluence.ConfluenceClient.Create (System.Uri confluenceUri, Dapplo.HttpExtensions.IHttpSettings httpSettings) [0x00000] in <c2e023c71b0d4013b45f2fad5d4ea254>:0 
  at Program+<Test>d__5.MoveNext () [0x0001b] in /Program.cs:22 

```

**Comment by CliffCawley** [comment]
I updated to the latest logger and httpextensions and now it works :)

**Comment by Lakritzator** [comment]
Sorry about the late answer, I have holidays, yes there was an issue on dotnet core and the logger.
Actually I believe there were some more issues with the latest Dapplo.HttpExtensions, I updated the nuget package to reflect the changes needed to make it work. Let me know if you have anything else not working.

**Comment by CliffCawley** [comment]
@Lakritzator Thanks! Enjoy your holidays :)

I'm compiling and running on a Mac but targetting .Net Framework 4.6.1 and another issue I've found is it seems there is a dependency on PresentationCore and PresentationFramework.

I believe they're for Windows Forms and WPF. Is it possible to remove that dependency? (I get a runtime exception because they can't be found)

**Comment by Lakritzator** [comment]
Huh, you can target the .NET Framework 4.6.1 without having the whole Framework, for me that doesn't make sense. The .NET Framework version of the HttpExtensions library has support for converting http responses to Bitmaps or BitmapSource, the later is the cause of having a reference.

Why don't you just target .NET Standard 1.3 or something, makes a lot more sense.

**Comment by CliffCawley** [comment]
>Why don't you just target .NET Standard 1.3 or something, makes a lot more sense.

While that's a great idea in theory, the problem is that I have many dependencies that don't have .Net Standard support yet so I can't upgrade :(

**Comment by CliffCawley** [comment]
Just to close the loop on this, I created local csproj files and added all the relevant files and fixed up all references for Dapplo.Confluence, Dapplo.HttpExtensions and Dapplo.HttpExtensions.JsonSimple, removing the project.json files and now I'm able to use Confluence! :)

**Comment by Lakritzator** [comment]
That somehow beats the reason why I made the project... and why there is NuGet.

**Comment by CliffCawley** [comment]
Sure, but what other option do I have right now? I switched my project to .Net standard, but running on VS for Mac there were issues importing dependencies as they haven't been updated to use .Net standard. 

When I attempted to create a blank project with just your library and run it, VS for Mac crashed hard every time just attempting to debug/run the test app. I think VS for Mac is not 100% ready for .Net standard yet.

I'm on a short time budget and when the next version of VS for Mac is released, I'll revisit again. For now, this was my solution given my constraints.

**Comment by Lakritzator** [comment]
I will also try to fix this, but I just tried to upgrade the project to 2017 and this causes some issues I need to solve. Currently these are turbulent times, with .NET Standard...

Soon, with 2.0, I hope to have less issues... the coming shimming functionality, where you can use not .NET Standard packages in a .NET Standard lib, is pretty cool.
