### ISSUE TITLE
How do I create a page as a child of another?

### ISSUE THREAD

**Issue by CliffCawley** [dapplo/Dapplo.Confluence#9]
I can't seem to figure out how to properly create a page of another page. I didn't see anything in the tests either, am I missing something?

**Comment by Lakritzator** [comment]
I'll check it out, don't know this from the top of my head.

**Comment by CliffCawley** [comment]
Were you able to find this out?

**Comment by CliffCawley** [comment]
Great, thanks for taking the time to make this happen!

I agree with your thinking about removing the suffix. No need if you're api supports only async anyway. If both then it's good to have the suffix since you couldn't overload the function with a differing return value.

Of course it'll break your api, but I suppose that's your decision depending on how many use it already :)

**Comment by Lakritzator** [comment]
I assume this is solved with the changes I made on the 22th of June 2017

**Comment by CliffCawley** [comment]
@Lakritzator Just to close the loop on this, thanks to the id argument you added, I was successfully able to add a page to the correct child!

Thank so much!
